//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGVIEC()
        {
            this.PHANCONG = new HashSet<PHANCONG>();
        }
    
        public int MaCongViec { get; set; }
        public string TenCV { get; set; }
        public int NguoiGiao { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaDuAn { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<int> TienDo { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
